import cmd

input("Voici la commande qui indique la version de cmd, usage:cmd.cmd_version()")
cmd.cmd_version()
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
input("Voici la commande qui crée un fichier texte, usage:cmd.cmd_new_txtFiles()")
cmd.cmd_new_txtFiles()
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
input("Voici la commande qui crée un dossier, usage:cmd.cmd_new_File()")
cmd.cmd_new_file()
