import cmd
input("Certaine commande marche pour les téléphone android elle seront indiquer avec un '&'.")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
input("Voici la commande qui indique la version de cmd, usage:cmd.version() '&'")
cmd.version()
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
input("Voici la commande qui crée un fichier texte, usage:cmd.new_txtFiles() '&'")
cmd.new_txtFiles()
input(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
input("Voici la commande qui crée un dossier, usage:cmd.new_file() '&'")
cmd.new_file()
input(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
input("Voici la commande qui permet de mettre en pause l'execution usage: cmd.pause() '&'")
cmd.pause()
input(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
input("Voici la commande qui sert a annuler un shutdown usage: cmd.no_shutdown()")
cmd.no_shutdown()
input(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
input("Voici la commande qui sert a ecrire dans le cmd usage cmd.echo()")
cmd.echo()
input(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
input("Voici la commande qui sert a ecrire la version de windows usage: cmd.win()")
cmd.win()
input(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
input("Voici la commande qui sert a allumer un terminal special usage: cmd.cmd()")
cmd.cmd()

